title: Lidia Puspa Ningtyas
logo: ![Image](https://github.com/user-attachments/assets/7b0f44e9-f6bb-43b6-8d58-2e4616f065df)
description: Data Analyst Portfolio
show download: true
theme: jekll-theme-minimal
